version: "3.5"

services:
  kdsu-webserver:
    build: .
    expose:
      - "80"
    ports:
      - "80:8001"
    networks:
      - kdsu_network
    restart: always

  icecast-stream:
    build: ./icecast
    ports:
      - 8000:8000
    networks:
      - kdsu_network
    restart: always

networks:
  kdsu_network:
    name: kdsu_backend_network

