version: "3.5"

services:
  kdsu-webserver:
    build: .
    expose:
      - "8001"
    networks:
      - kdsu_network
    restart: always

  icecast-stream:
    build: ./icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=aaa
      - ICECAST_ADMIN_PASSWORD=test
      - ICECAST_PASSWORD=test
      - ICECAST_RELAY_PASSWORD=test
    ports:
      - 8000:8000
    networks:
      - kdsu_network
    restart: always

  kdsu-proxy:
    build: ./kdsu-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - kdsu_network
    restart: always

networks:
  kdsu_network:
    name: kdsu_backend_network
